services:
  traefik:
    image: "traefik:v3.5.0"
    ports:
      - "9080:80"
      - "8080:8080"
    volumes:
      - "./configs/traefik-config.yml:/etc/traefik/traefik.yml:ro"
      - "./configs/http.yml:/etc/traefik/configs/http.yml:ro"
      - "./:/plugins-local/src/github.com/sevensolutions/rocket-traefik-plugin:ro"

  whoami:
    image: "traefik/whoami:latest"

  rocket-mock:
    image: "golang:1.23-alpine"
    working_dir: /app
    environment:
      GOCACHE: /tmp/gocache
    volumes:
      - "./:/app:ro"
    command: ["go", "run", "./mock/rocket-mock"]
    ports:
      - "9081:80"
